# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Resume
subtitle: ''
description: ''
keywords:
author:  Xiangyu chen
language: en
timezone: ''

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: http://example.com
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: hexo-mtics-resume
theme_config: 
  title: Resume
  footer:
    enable: false # decide where you want to show  your footer
    copyright:  # customize your copyright in footer, e.g. © 2019-2020 Zhiwei Li
      startYear: 2023
      currentYear: 2023
      author: xychen
      link: https://cretaceous-creature.github.io
      beian: 

  ################################
  #     Write your resume Here   #
  ################################
  resume:
    name: Xiangyu Chen
    jobtitle:  Robotics Scientist
    portrait: ./img/sakura.jpg # author's portrait
    contact:
      - icon: fa-envelope
        text: xychen@jsk.imi.i.u-tokyo.ac.jp
      - icon: fa-phone-square
        text: (+86)18810357993
        link: poss.pku.edu.cn
      - icon: fa-globe
        text: (+81)080-5649-1118
        link: www.jsk.t.u-tokyo.ac.jp
      - icon: fa-google
        text: Google Scholar
        link: https://scholar.google.com/citations?user=SE11E_oAAAAJ&hl=zh-CN
    education:
      - university: The University of Tokyo, Japan
        duration: 2017
        location: Ph.D
        major: Robotics, AI. JSK lab, Creative Informatics
      - university: Peking University, China
        duration: 2014
        location: Master
        major: CV, Robotics. Poss Lab, Information Science and Technology   
      - university: Hainan University, China
        duration: 2011
        location: Bachelor
        major:  Electronics Engineering, Information Science and Technology
    experience:
      - title: Director of Robotic ARM Department
        duration: 2021 - Now
        company: Xpeng Robotics
        description: Director of Xpeng Robotics ARM Business, manage a team of 30 researchers&engineers. Build up 2 type of robot arms for Xpeng quadruped robot. Develop intelligent manipulation function for Xpeng quadruped robot. 
      - title: Senior Researcher, Robotics X
        duration: 2018 - 2021
        company: Tencent Corp.
        description: Project Owner of Tencent's Quadruped Project. Create Tencent's robot 'Max' from scratch.
      - title: Postdoc Researcher
        duration: 2017-2018
        company: The University of Tokyo, Peking University
        description: Legged Robots, military UGV research.
    projects:
      - name: "'Second Prize' in GM(General Motors) Vehicle Networking Competition, Beijing, China"
        description: Team Leader, Peking University
        contribution: 2013
      - name: "Winner of the First Tomato Robot Harvesting Challenge Competition, Kyushu, Japan"
        description: Member of JSK Team, The University of Tokyo 
        contribution: 2014
      - name: "DARPA Robotics Challenge(DRC) Final, Fairplex in Pomona, USA"
        description: Member of JSK Team, The University of Tokyo 
        contribution: 2015
      - name: "Best Student Paper Award of IEEE Advanced Intelligent Mechatronics (AIM)"
        description: Second Author
        contribution: 2017
      - name: "Mohamed Bin Zayed International Robotic Challenge(MBZIRC), Abu Dhabi, UAE"
        description: Key Member of Selected Sponsored Team($350,000)
        contribution: 2017
      - name: "Best Paper Award（UAV） of IEEE Robotics and Automation (ICRA)"
        description: Co-Author
        contribution: 2018
      - name: "Silver Prize of Tencent's Technical Breakthrough Award, Shenzhen, China"
        description: Project Owner
        contribution: 2020
      
    skills:
      - title: Language
        items: Chinese (Native), English (Fluent), Japanese (Fluent)
      - title: Research Interests
        items: Legged Robots, Drone, Robot Manipulation, Reinforcement Learning
      - title: Publications
        items: Plz refer to the google scholar


# Deployment
deploy:
  type: git
  repo: git@github.com:cretaceous-creature/cretaceous-creature.github.io.git
  branch: gh-pages
